// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int n = Integer.parseInt(args[0]);
		int under = 0;
		int over = 0;

		for (int i = 0; i < n; i++)
		{
			double random1 = Math.random();
			if (random1 < 0.5){
				under++;
			}
			else {
				over++;
			}
		}
		System.out.println("> 0.5: " + over + " times");
		System.out.println("<= 0.5: " + under + " times");

		if (over > under){
			System.out.print("Ratio: " + ((double)under / (double)over));
		}
		else if (over < under){
			System.out.print("Ratio: " + ((double)over / (double)under));
		}
		else {
			System.out.print("Ratio: " + ((double)over / (double)under));
		}

	}
}
